const SITE='https://huangguoai.com';
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36';
const KEY='f5d965df75336270', IV='97b60394abc2fbe1';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'*'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});
const fix=u=>{if(!u)return '';u=String(u).replace(/&amp;/g,'&');if(u.startsWith('//'))return 'https:'+u;if(u.startsWith('/'))return SITE+u;return u};
const text=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();
async function html(url,ref=SITE+'/'){const r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,*/*;q=0.8','Referer':ref}});return r.ok?r.text():''}
function cards(h){const out=[],seen=new Set();const re=/<div[^>]*class="[^"]*hg-drama-card[^"]*"[^>]*>([\s\S]*?)(?=<div[^>]*class="[^"]*hg-drama-card|$)/g;let m;while((m=re.exec(h))){const b=m[0],a=b.match(/href="[^"]*\/(?:detail|video)\/(\d+)\//);if(!a||seen.has(a[1]))continue;const t=b.match(/hg-drama-card__title[^>]*>([\s\S]*?)<\/a>/),im=b.match(/(?:data-src|src)="([^"]+)"/),ep=b.match(/hg-drama-card__episode[^>]*>([\s\S]*?)<\/span>/),sc=b.match(/hg-drama-card__score[^>]*>([\s\S]*?)<\/span>/);const name=text(t?.[1]);if(!name)continue;seen.add(a[1]);out.push({vod_id:a[1],vod_name:name,vod_pic:im?`/media?url=${encodeURIComponent(fix(im[1]))}`:'',vod_remarks:[ep&&text(ep[1]),sc&&text(sc[1])].filter(Boolean).join(' · ')})}return out}
function episodes(h,id){const out=[],seen=new Set(),re=/<a[^>]*href="([^"]+)"[^>]*>[\s\S]*?<\/a>/g;let m;while((m=re.exec(h))){const href=fix(m[1]);if(!href.includes('/video/'+id+'/')&&!href.includes('/detail/'+id+'/'))continue;const ep=(href.match(/\/ep-(\d+)\//)||m[0].match(/(\d+)/))?.[1]||'1';if(seen.has(ep))continue;seen.add(ep);out.push({ep,url:href})}return out.length?out.sort((a,b)=>+a.ep-+b.ep):[{ep:'1',url:SITE+'/video/'+id+'/'}]}
async function decrypt(b64){try{const raw=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if(raw.length%16)return null;const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(KEY),'AES-CBC',false,['decrypt']);let p=new Uint8Array(await crypto.subtle.decrypt({name:'AES-CBC',iv:new TextEncoder().encode(IV)},k,raw));const n=p[p.length-1];if(n>0&&n<=16&&p.slice(-n).every(x=>x===n))p=p.slice(0,-n);return p}catch{return null}}
function mime(b){if(b[0]===0xff&&b[1]===0xd8)return'image/jpeg';if(b[0]===0x89&&b[1]===0x50)return'image/png';if(b[0]===0x52&&b[1]===0x49)return'image/webp';return'application/octet-stream'}
async function media(u){const r=await fetch(u,{headers:{'User-Agent':UA,'Referer':SITE+'/'}});const raw=await r.arrayBuffer();const b=new Uint8Array(raw);if((r.headers.get('content-type')||'').startsWith('image/'))return new Response(raw,{headers:{...cors,'content-type':r.headers.get('content-type'),'cache-control':'public,max-age=3600'}});const p=await decrypt(new TextDecoder().decode(b));return new Response(p||new Uint8Array([137,80,78,71,13,10,26,10]),{headers:{...cors,'content-type':p?mime(p):'image/png','cache-control':'public,max-age=3600'}})}
export default {async fetch(req){if(req.method==='OPTIONS')return new Response(null,{headers:cors});const u=new URL(req.url);try{if(u.pathname==='/media'){const x=u.searchParams.get('url');if(!/^https?:\/\//.test(x||''))return new Response(null,{status:400,headers:cors});return media(x)}if(!u.pathname.startsWith('/api'))return new Response('黄果解析 Worker API',{headers:{...cors,'content-type':'text/plain;charset=utf-8'}});const p=u.pathname.slice(4);if(p==='/'){return json({name:'黄果解析 API',status:'ok'})}if(p==='/detail/'+p.split('/')[2]){}if(p.startsWith('/detail/')){const id=p.split('/')[2];const h=await html(SITE+'/video/'+id+'/');const title=text((h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1])||id;const im=(h.match(/(?:data-src|src)="([^"]+)"/)||[])[1];return json({list:[{vod_id:id,vod_name:title,vod_pic:im?`/media?url=${encodeURIComponent(fix(im))}`:'',episodes:episodes(h,id)}]})}if(p==='/play'){const h=await html(decodeURIComponent(u.searchParams.get('url')||''));const d=(h.match(/id=["']videoInitialData["'][^>]*>([\s\S]*?)<\/script>/i)||[])[1];let play='';try{const x=JSON.parse(d);play=x.epPlaySrcs?.[u.searchParams.get('ep')||'1']||x.videoSrc||''}catch{};if(!play)play=(h.match(/https?:\\?\/\\?\/[^"'<>\s]+?\.m3u8[^"'<>\s]*/i)||[])[0]||'';return json({url:play.replace(/\\\//g,'/')})}if(p.startsWith('/search/')){const q=decodeURIComponent(p.split('/')[2]||'');return json({list:cards(await html(SITE+'/search/video/'+encodeURIComponent(q)+'/'))})}const path=p||'/';return json({list:cards(await html(SITE+path))})}catch(e){return json({error:'源站请求失败',detail:String(e.message||e)},502)}}};
