const SITE = 'https://huangguoai.com';
const CORS = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'*'};
const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{...CORS,'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});
const absolute = (value) => !value ? '' : value.startsWith('//') ? 'https:'+value : value.startsWith('/') ? SITE+value : value;
const clean = (value) => String(value||'').replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').trim();
const validImage = (value) => value && !/mc\.yandex|google-analytics|pixel|tracker/i.test(value);
async function fetchHtml(url) { const response = await fetch(url, {headers:{'User-Agent':'Mozilla/5.0','Referer':SITE+'/'}}); return response.ok ? response.text() : ''; }
function proxiedImage(value) { return validImage(value) ? '/media?url='+encodeURIComponent(absolute(value)) : ''; }
function initialCover(html) { const match = html.match(/id=["']videoInitialData["'][^>]*>([\s\S]*?)<\/script>/i); if (match) { try { const data=JSON.parse(match[1]); if (validImage(data.coverSrc)) return data.coverSrc; } catch {} } return ''; }
function parseCards(html) { const result=[], seen=new Set(), re=/<a\b[^>]*href=["']([^"']*\/video\/(\d+)\/)["'][^>]*>([\s\S]*?)<\/a>/gi; let match; while ((match=re.exec(html))) { const id=match[2]; if (seen.has(id)) continue; const name=clean(match[3]).replace(/全集在线观看/g,'').trim(); if (!name || /^\d+$/.test(name)) continue; const around=html.slice(Math.max(0,match.index-3000), Math.min(html.length,match.index+3000)); const images=[...around.matchAll(/(?:data-src|data-original|src)=["']([^"']+)["']/gi)].map(item=>item[1]).filter(validImage); const image=images.find(item=>/\.(jpg|jpeg|png|webp)(\?|$)/i.test(item)) || images[0] || ''; seen.add(id); result.push({vod_id:id,vod_name:name,vod_pic:proxiedImage(image),vod_remarks:''}); } return result; }
function parseEpisodes(id, html) { const result=[{ep:'1',url:SITE+'/video/'+id+'/'}], seen=new Set(['1']), re=new RegExp('href=["\\']([^"\\']*\\/video\\/'+id+'\\/ep-(\\d+)\\/)["\\']','gi'); let match; while ((match=re.exec(html))) { if (!seen.has(match[2])) { seen.add(match[2]); result.push({ep:match[2],url:absolute(match[1])}); } } return result.sort((a,b)=>Number(a.ep)-Number(b.ep)); }
async function proxyImage(url) { if (!/^https?:\/\//i.test(url||'')) return new Response(null,{status:400,headers:CORS}); const response=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Referer':SITE+'/'}}); return new Response(response.body,{status:response.status,headers:{...CORS,'content-type':response.headers.get('content-type')||'image/png','cache-control':'public,max-age=86400'}}); }
async function handle(request) { if (request.method==='OPTIONS') return new Response(null,{headers:CORS}); const url=new URL(request.url); const path=url.pathname.startsWith('/api') ? url.pathname.slice(4) : ''; try { if (url.pathname==='/media') return proxyImage(url.searchParams.get('url')); if (!url.pathname.startsWith('/api')) return new Response('Huangguo Parser API',{headers:{...CORS,'content-type':'text/plain;charset=utf-8'}}); if (path==='/') return json({status:'ok'}); if (path.startsWith('/search/')) { const keyword=decodeURIComponent(path.split('/')[2]||''); return json({list:parseCards(await fetchHtml(SITE+'/search/video/'+encodeURIComponent(keyword)+'/'))}); } if (path.startsWith('/detail/')) { const id=path.split('/')[2], html=await fetchHtml(SITE+'/video/'+id+'/'), title=clean((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1])||id), image=initialCover(html)||((html.match(/<meta[^>]+(?:property|name)=["']og:image["'][^>]+content=["']([^"']+)["']/i)||[])[1]); return json({list:[{vod_id:id,vod_name:title,vod_pic:proxiedImage(image),episodes:parseEpisodes(id,html)}]}); } if (path==='/play') { const page=decodeURIComponent(url.searchParams.get('url')||''), episode=url.searchParams.get('ep')||'1', html=await fetchHtml(page), data=(html.match(/id=["']videoInitialData["'][^>]*>([\s\S]*?)<\/script>/i)||[])[1]; let stream=''; try { const parsed=JSON.parse(data); stream=parsed.epPlaySrcs?.[episode]||parsed.videoSrc||''; } catch {} if (!stream) stream=(html.match(/https?:\\?\/\\?\/[^"'<>\s]+?\.m3u8(?:\?[^"'<>\s]*)?/i)||[])[0]||''; return json({url:stream.replace(/\\\//g,'/')}); } return json({list:parseCards(await fetchHtml(SITE+(path||'/')))}); } catch (error) { return json({error:String(error?.message||error)},502); } }
addEventListener('fetch', event => event.respondWith(handle(event.request)));